# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  heartbeat:
    class: HeartbeatJob
    schedule: every 5 minutes
  process_due_sources:
    class: ProcessDueSourcesJob
    queue: default
    schedule: every 15 minutes

test:
  heartbeat:
    class: HeartbeatJob
    schedule: every 5 minutes
  process_due_sources:
    class: ProcessDueSourcesJob
    queue: default
    schedule: every 15 minutes

production:
  heartbeat:
    class: HeartbeatJob
    schedule: every 5 minutes
  process_due_sources:
    class: ProcessDueSourcesJob
    queue: default
    schedule: every 15 minutes
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
