# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  heartbeat:
    class: HeartbeatJob
    schedule: every 5 minutes
  process_due_sources:
    class: ProcessDueSourcesJob
    queue: default
    schedule: every 15 minutes
  publish_scheduled_content:
    class: PublishScheduledContentJob
    queue: default
    schedule: every minute

test:
  heartbeat:
    class: HeartbeatJob
    schedule: every 5 minutes
  process_due_sources:
    class: ProcessDueSourcesJob
    queue: default
    schedule: every 15 minutes
  publish_scheduled_content:
    class: PublishScheduledContentJob
    queue: default
    schedule: every minute

production:
  heartbeat:
    class: HeartbeatJob
    schedule: every 5 minutes
  process_due_sources:
    class: ProcessDueSourcesJob
    queue: default
    schedule: every 15 minutes
  publish_scheduled_content:
    class: PublishScheduledContentJob
    queue: default
    schedule: every minute
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  send_weekly_digest_emails:
    class: SendDigestEmailsJob
    queue: mailers
    args: [{ frequency: "weekly" }]
    schedule: every Monday at 9am
  send_daily_digest_emails:
    class: SendDigestEmailsJob
    queue: mailers
    args: [{ frequency: "daily" }]
    schedule: every day at 8am
